# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/SCV/Desktop/PPRE/ppremoveedit.ui'
#
# Created: Thu Apr 16 15:37:17 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MoveEditDlg(object):
    def setupUi(self, MoveEditDlg):
        MoveEditDlg.setObjectName("MoveEditDlg")
        MoveEditDlg.resize(862, 211)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PPRE.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MoveEditDlg.setWindowIcon(icon)
        self.chooseMove = QtGui.QComboBox(MoveEditDlg)
        self.chooseMove.setGeometry(QtCore.QRect(20, 10, 141, 27))
        self.chooseMove.setObjectName("chooseMove")
        self.basePower = QtGui.QSpinBox(MoveEditDlg)
        self.basePower.setGeometry(QtCore.QRect(400, 100, 58, 29))
        self.basePower.setMaximum(255)
        self.basePower.setObjectName("basePower")
        self.effectChance = QtGui.QSpinBox(MoveEditDlg)
        self.effectChance.setGeometry(QtCore.QRect(590, 100, 58, 29))
        self.effectChance.setMaximum(255)
        self.effectChance.setObjectName("effectChance")
        self.accuracy = QtGui.QSpinBox(MoveEditDlg)
        self.accuracy.setGeometry(QtCore.QRect(460, 100, 58, 29))
        self.accuracy.setMaximum(255)
        self.accuracy.setObjectName("accuracy")
        self.pp = QtGui.QSpinBox(MoveEditDlg)
        self.pp.setGeometry(QtCore.QRect(530, 100, 58, 29))
        self.pp.setMaximum(255)
        self.pp.setObjectName("pp")
        self.unk1 = QtGui.QSpinBox(MoveEditDlg)
        self.unk1.setGeometry(QtCore.QRect(710, 100, 58, 29))
        self.unk1.setMaximum(255)
        self.unk1.setObjectName("unk1")
        self.priority = QtGui.QSpinBox(MoveEditDlg)
        self.priority.setGeometry(QtCore.QRect(650, 100, 58, 29))
        self.priority.setMaximum(255)
        self.priority.setObjectName("priority")
        self.unk2 = QtGui.QSpinBox(MoveEditDlg)
        self.unk2.setGeometry(QtCore.QRect(770, 100, 58, 29))
        self.unk2.setMaximum(255)
        self.unk2.setObjectName("unk2")
        self.catkDesc = QtGui.QPlainTextEdit(MoveEditDlg)
        self.catkDesc.setGeometry(QtCore.QRect(20, 130, 251, 64))
        self.catkDesc.setObjectName("catkDesc")
        self.atkDesc = QtGui.QPlainTextEdit(MoveEditDlg)
        self.atkDesc.setGeometry(QtCore.QRect(20, 60, 251, 64))
        self.atkDesc.setObjectName("atkDesc")
        self.effect = QtGui.QComboBox(MoveEditDlg)
        self.effect.setGeometry(QtCore.QRect(280, 10, 321, 27))
        self.effect.setObjectName("effect")
        self.type = QtGui.QComboBox(MoveEditDlg)
        self.type.setGeometry(QtCore.QRect(280, 60, 111, 27))
        self.type.setObjectName("type")
        self.category = QtGui.QComboBox(MoveEditDlg)
        self.category.setGeometry(QtCore.QRect(400, 60, 101, 27))
        self.category.setObjectName("category")
        self.category.addItem(QtCore.QString())
        self.category.addItem(QtCore.QString())
        self.category.addItem(QtCore.QString())
        self.target = QtGui.QComboBox(MoveEditDlg)
        self.target.setGeometry(QtCore.QRect(520, 60, 231, 27))
        self.target.setObjectName("target")
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.target.addItem(QtCore.QString())
        self.ctype = QtGui.QComboBox(MoveEditDlg)
        self.ctype.setGeometry(QtCore.QRect(280, 100, 111, 27))
        self.ctype.setObjectName("ctype")

        self.retranslateUi(MoveEditDlg)
        QtCore.QObject.connect(self.chooseMove, QtCore.SIGNAL("currentIndexChanged(int)"), MoveEditDlg.moveChanged)
        QtCore.QMetaObject.connectSlotsByName(MoveEditDlg)

    def retranslateUi(self, MoveEditDlg):
        MoveEditDlg.setWindowTitle(QtGui.QApplication.translate("MoveEditDlg", "Move Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.category.setItemText(0, QtGui.QApplication.translate("MoveEditDlg", "Physical", None, QtGui.QApplication.UnicodeUTF8))
        self.category.setItemText(1, QtGui.QApplication.translate("MoveEditDlg", "Special", None, QtGui.QApplication.UnicodeUTF8))
        self.category.setItemText(2, QtGui.QApplication.translate("MoveEditDlg", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(0, QtGui.QApplication.translate("MoveEditDlg", "Choosen Opponent", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(1, QtGui.QApplication.translate("MoveEditDlg", "Chosen Opponent, Random Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(2, QtGui.QApplication.translate("MoveEditDlg", "Random Opponent", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(3, QtGui.QApplication.translate("MoveEditDlg", "Opponents on Field", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(4, QtGui.QApplication.translate("MoveEditDlg", "All Other on Field", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(5, QtGui.QApplication.translate("MoveEditDlg", "Self", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(6, QtGui.QApplication.translate("MoveEditDlg", "Team", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(7, QtGui.QApplication.translate("MoveEditDlg", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.target.setItemText(8, QtGui.QApplication.translate("MoveEditDlg", "Opponent’s Team", None, QtGui.QApplication.UnicodeUTF8))

