# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ppretredit.ui'
#
# Created: Mon Jan 11 21:22:20 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TrainerEditDlg(object):
    def setupUi(self, TrainerEditDlg):
        TrainerEditDlg.setObjectName("TrainerEditDlg")
        TrainerEditDlg.resize(799, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PPRE.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TrainerEditDlg.setWindowIcon(icon)
        self.chooseTrainer = QtGui.QComboBox(TrainerEditDlg)
        self.chooseTrainer.setGeometry(QtCore.QRect(150, 5, 181, 27))
        self.chooseTrainer.setObjectName("chooseTrainer")
        self.curtrLabel = QtGui.QLabel(TrainerEditDlg)
        self.curtrLabel.setGeometry(QtCore.QRect(20, 5, 121, 20))
        self.curtrLabel.setObjectName("curtrLabel")
        self.maintab = QtGui.QTabWidget(TrainerEditDlg)
        self.maintab.setGeometry(QtCore.QRect(30, 55, 731, 541))
        self.maintab.setTabPosition(QtGui.QTabWidget.North)
        self.maintab.setObjectName("maintab")
        self.tab0 = QtGui.QWidget()
        self.tab0.setObjectName("tab0")
        self.gridLayoutWidget = QtGui.QWidget(self.tab0)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(5, 5, 711, 492))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.class_2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.class_2.setObjectName("class_2")
        self.gridLayout.addWidget(self.class_2, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.item1 = QtGui.QComboBox(self.gridLayoutWidget)
        self.item1.setObjectName("item1")
        self.gridLayout_2.addWidget(self.item1, 0, 0, 1, 1)
        self.item3 = QtGui.QComboBox(self.gridLayoutWidget)
        self.item3.setObjectName("item3")
        self.gridLayout_2.addWidget(self.item3, 1, 0, 1, 1)
        self.item2 = QtGui.QComboBox(self.gridLayoutWidget)
        self.item2.setObjectName("item2")
        self.gridLayout_2.addWidget(self.item2, 0, 1, 1, 1)
        self.item4 = QtGui.QComboBox(self.gridLayoutWidget)
        self.item4.setObjectName("item4")
        self.gridLayout_2.addWidget(self.item4, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.doubleBool = QtGui.QCheckBox(self.gridLayoutWidget)
        self.doubleBool.setObjectName("doubleBool")
        self.gridLayout.addWidget(self.doubleBool, 9, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 11, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.itemBool = QtGui.QCheckBox(self.gridLayoutWidget)
        self.itemBool.setObjectName("itemBool")
        self.gridLayout_4.addWidget(self.itemBool, 0, 1, 1, 1)
        self.attackBool = QtGui.QCheckBox(self.gridLayoutWidget)
        self.attackBool.setObjectName("attackBool")
        self.gridLayout_4.addWidget(self.attackBool, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 1, 1, 1)
        self.pokenum = QtGui.QSpinBox(self.gridLayoutWidget)
        self.pokenum.setMaximum(6)
        self.pokenum.setObjectName("pokenum")
        self.gridLayout.addWidget(self.pokenum, 1, 1, 1, 1)
        self.uc = QtGui.QSpinBox(self.gridLayoutWidget)
        self.uc.setObjectName("uc")
        self.gridLayout.addWidget(self.uc, 5, 1, 1, 1)
        self.ud = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ud.setObjectName("ud")
        self.gridLayout.addWidget(self.ud, 6, 1, 1, 1)
        self.ue = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ue.setObjectName("ue")
        self.gridLayout.addWidget(self.ue, 7, 1, 1, 1)
        self.uf = QtGui.QSpinBox(self.gridLayoutWidget)
        self.uf.setObjectName("uf")
        self.gridLayout.addWidget(self.uf, 8, 1, 1, 1)
        self.u11 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.u11.setObjectName("u11")
        self.gridLayout.addWidget(self.u11, 10, 1, 1, 1)
        self.u12 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.u12.setObjectName("u12")
        self.gridLayout.addWidget(self.u12, 11, 1, 1, 1)
        self.u13 = QtGui.QSpinBox(self.gridLayoutWidget)
        self.u13.setObjectName("u13")
        self.gridLayout.addWidget(self.u13, 12, 1, 1, 1)
        self.trname = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trname.sizePolicy().hasHeightForWidth())
        self.trname.setSizePolicy(sizePolicy)
        self.trname.setObjectName("trname")
        self.gridLayout.addWidget(self.trname, 0, 1, 1, 1)
        self.maintab.addTab(self.tab0, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(50, 50, 600, 75))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtGui.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 175, 600, 75))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtGui.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(50, 300, 600, 75))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(55, 20, 166, 18))
        self.label_2.setObjectName("label_2")
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(55, 145, 211, 18))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(55, 270, 231, 18))
        self.label_22.setObjectName("label_22")
        self.maintab.addTab(self.tab, "")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(50, 50, 536, 236))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spec1 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.spec1.setObjectName("spec1")
        self.gridLayout_3.addWidget(self.spec1, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.pokelvl1 = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.pokelvl1.setObjectName("pokelvl1")
        self.gridLayout_3.addWidget(self.pokelvl1, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.pokeItem1 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.pokeItem1.setObjectName("pokeItem1")
        self.gridLayout_3.addWidget(self.pokeItem1, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 3, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.attack1_1 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.attack1_1.setObjectName("attack1_1")
        self.gridLayout_5.addWidget(self.attack1_1, 0, 0, 1, 1)
        self.attack1_2 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.attack1_2.setObjectName("attack1_2")
        self.gridLayout_5.addWidget(self.attack1_2, 0, 1, 1, 1)
        self.attack1_3 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.attack1_3.setObjectName("attack1_3")
        self.gridLayout_5.addWidget(self.attack1_3, 1, 0, 1, 1)
        self.attack1_4 = QtGui.QComboBox(self.gridLayoutWidget_3)
        self.attack1_4.setObjectName("attack1_4")
        self.gridLayout_5.addWidget(self.attack1_4, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 3, 1, 1, 1)
        self.maintab.addTab(self.tab1, "")
        self.saveButton = QtGui.QPushButton(TrainerEditDlg)
        self.saveButton.setGeometry(QtCore.QRect(410, 5, 126, 28))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(TrainerEditDlg)
        self.maintab.setCurrentIndex(0)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL("pressed()"), TrainerEditDlg.saveTrainer)
        QtCore.QMetaObject.connectSlotsByName(TrainerEditDlg)

    def retranslateUi(self, TrainerEditDlg):
        TrainerEditDlg.setWindowTitle(QtGui.QApplication.translate("TrainerEditDlg", "PPRE: Pokemon Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.curtrLabel.setText(QtGui.QApplication.translate("TrainerEditDlg", "Current Trainer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TrainerEditDlg", "Trainer Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TrainerEditDlg", "Number of Pokemon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TrainerEditDlg", "Trainer Class", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TrainerEditDlg", "Trainer Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TrainerEditDlg", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TrainerEditDlg", "0Ch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TrainerEditDlg", "0Dh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TrainerEditDlg", "0Eh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TrainerEditDlg", "0Fh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TrainerEditDlg", "Double Battle", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleBool.setText(QtGui.QApplication.translate("TrainerEditDlg", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TrainerEditDlg", "11h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TrainerEditDlg", "12h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TrainerEditDlg", "13h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TrainerEditDlg", "Pokemon have items", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TrainerEditDlg", "Pokemon have different attacks", None, QtGui.QApplication.UnicodeUTF8))
        self.itemBool.setText(QtGui.QApplication.translate("TrainerEditDlg", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.attackBool.setText(QtGui.QApplication.translate("TrainerEditDlg", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.maintab.setTabText(self.maintab.indexOf(self.tab0), QtGui.QApplication.translate("TrainerEditDlg", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TrainerEditDlg", "Introduction Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("TrainerEditDlg", "Defeated Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("TrainerEditDlg", "Won Text", None, QtGui.QApplication.UnicodeUTF8))
        self.maintab.setTabText(self.maintab.indexOf(self.tab), QtGui.QApplication.translate("TrainerEditDlg", "Quotes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TrainerEditDlg", "Pokemon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("TrainerEditDlg", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("TrainerEditDlg", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TrainerEditDlg", "Extra Attacks", None, QtGui.QApplication.UnicodeUTF8))
        self.maintab.setTabText(self.maintab.indexOf(self.tab1), QtGui.QApplication.translate("TrainerEditDlg", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("TrainerEditDlg", "Save", None, QtGui.QApplication.UnicodeUTF8))

